api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json:
            mime_types: [ 'application/json' ]
        jsonld:
            mime_types: [ 'application/ld+json' ]
        html:
            mime_types: [ 'text/html' ]

    patch_formats: []
    error_formats:
        jsonproblem:
            mime_types: [ 'application/problem+json' ]

        jsonld:
            mime_types: [ 'application/ld+json' ]
    swagger:
        versions: [3]
