api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json:
            mime_types: [ 'application/json' ]
        jsonld:
            mime_types: [ 'application/ld+json' ]
        html:
            mime_types: [ 'text/html' ]

    patch_formats: []
    error_formats:
        jsonproblem:
            mime_types: [ 'application/problem+json' ]

        jsonld:
            mime_types: [ 'application/ld+json' ]
    swagger:
        versions: [3]

    collection:
        pagination:
            items_per_page: 100 # Default value
            client_items_per_page: true # Disabled by default
            items_per_page_parameter_name: itemsPerPage # Default value
